(cl:defpackage ur_msgs-msg
  (:use )
  (:export
   "<MASTERBOARDDATAMSG>"
   "MASTERBOARDDATAMSG"
   "<IOSTATES>"
   "IOSTATES"
   "<ANALOG>"
   "ANALOG"
   "<DIGITAL>"
   "DIGITAL"
   "<ROBOTSTATERTMSG>"
   "ROBOTSTATERTMSG"
   "<FOLLOWCARTESIANTRAJECTORYRESULT>"
   "FOLLOWCARTESIANTRAJECTORYRESULT"
   "<FOLLOWCARTESIANTRAJECTORYGOAL>"
   "FOLLOWCARTESIANTRAJECTORYGOAL"
   "<FOLLOWCARTESIANTRAJECTORYACTIONFEEDBACK>"
   "FOLLOWCARTESIANTRAJECTORYACTIONFEEDBACK"
   "<FOLLOWCARTESIANTRAJECTORYACTIONGOAL>"
   "FOLLOWCARTESIANTRAJECTORYACTIONGOAL"
   "<FOLLOWCARTESIANTRAJECTORYACTIONRESULT>"
   "FOLLOWCARTESIANTRAJECTORYACTIONRESULT"
   "<FOLLOWCARTESIANTRAJECTORYFEEDBACK>"
   "FOLLOWCARTESIANTRAJECTORYFEEDBACK"
   "<FOLLOWCARTESIANTRAJECTORYACTION>"
   "FOLLOWCARTESIANTRAJECTORYACTION"
  ))

