(cl:in-package ur_msgs-msg)
(cl:export '(DIGITAL_IN_STATES-VAL
          DIGITAL_IN_STATES
          DIGITAL_OUT_STATES-VAL
          DIGITAL_OUT_STATES
          FLAG_STATES-VAL
          FLAG_STATES
          ANALOG_IN_STATES-VAL
          ANALOG_IN_STATES
          ANALOG_OUT_STATES-VAL
          ANALOG_OUT_STATES
          MASTER_SAFETY_STATE-VAL
          MASTER_SAFETY_STATE
          MASTER_ONOFF_STATE-VAL
          MASTER_ONOFF_STATE
))