/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/bdml/catkin_ws/src/universal_robot/ur_msgs/srv/SetIO.srv
 *
 */


#ifndef UR_MSGS_MESSAGE_SETIO_H
#define UR_MSGS_MESSAGE_SETIO_H

#include <ros/service_traits.h>


#include <ur_msgs/SetIORequest.h>
#include <ur_msgs/SetIOResponse.h>


namespace ur_msgs
{

struct SetIO
{

typedef SetIORequest Request;
typedef SetIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIO
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::SetIO > {
  static const char* value()
  {
    return "9891d388d5518ebedde6430899d4897a";
  }

  static const char* value(const ::ur_msgs::SetIO&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::SetIO > {
  static const char* value()
  {
    return "ur_msgs/SetIO";
  }

  static const char* value(const ::ur_msgs::SetIO&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::SetIORequest> should match 
// service_traits::MD5Sum< ::ur_msgs::SetIO > 
template<>
struct MD5Sum< ::ur_msgs::SetIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetIO >::value();
  }
  static const char* value(const ::ur_msgs::SetIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetIORequest> should match 
// service_traits::DataType< ::ur_msgs::SetIO > 
template<>
struct DataType< ::ur_msgs::SetIORequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetIO >::value();
  }
  static const char* value(const ::ur_msgs::SetIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::SetIOResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::SetIO > 
template<>
struct MD5Sum< ::ur_msgs::SetIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetIO >::value();
  }
  static const char* value(const ::ur_msgs::SetIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetIOResponse> should match 
// service_traits::DataType< ::ur_msgs::SetIO > 
template<>
struct DataType< ::ur_msgs::SetIOResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetIO >::value();
  }
  static const char* value(const ::ur_msgs::SetIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETIO_H
