/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/bdml/catkin_ws/src/universal_robot/ur_msgs/srv/SetPayload.srv
 *
 */


#ifndef UR_MSGS_MESSAGE_SETPAYLOAD_H
#define UR_MSGS_MESSAGE_SETPAYLOAD_H

#include <ros/service_traits.h>


#include <ur_msgs/SetPayloadRequest.h>
#include <ur_msgs/SetPayloadResponse.h>


namespace ur_msgs
{

struct SetPayload
{

typedef SetPayloadRequest Request;
typedef SetPayloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPayload
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::SetPayload > {
  static const char* value()
  {
    return "7f12eb632882cb73e5721178d0073e39";
  }

  static const char* value(const ::ur_msgs::SetPayload&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::SetPayload > {
  static const char* value()
  {
    return "ur_msgs/SetPayload";
  }

  static const char* value(const ::ur_msgs::SetPayload&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::SetPayloadRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::SetPayload > 
template<>
struct MD5Sum< ::ur_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetPayloadRequest> should match 
// service_traits::DataType< ::ur_msgs::SetPayload > 
template<>
struct DataType< ::ur_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::SetPayloadResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::SetPayload > 
template<>
struct MD5Sum< ::ur_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetPayloadResponse> should match 
// service_traits::DataType< ::ur_msgs::SetPayload > 
template<>
struct DataType< ::ur_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetPayload >::value();
  }
  static const char* value(const ::ur_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETPAYLOAD_H
